services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
